In [36]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

CSV_PATH = "../data/fuel_prices.csv"  # Change if needed
BATCH_SIZE = 200

df = pd.read_csv(CSV_PATH)

print(df.shape)
df.head()


# Ensure required columns exist
for col in ["Address", "City", "State"]:
    df[col] = df[col].fillna("").astype(str).str.strip()

for col in ["latitude", "longitude"]:
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = pd.to_numeric(df[col], errors="coerce")

if "geocode_status" not in df.columns:
    df["geocode_status"] = pd.NA

df["geocode_status"] = df["geocode_status"].astype("string")

# A normalized key identifies duplicate locations.
def make_location_key(row):
    return "|".join(
        str(row[col]).strip().casefold()
        for col in ["Address", "City", "State"]
    )

df["_location_key"] = df.apply(make_location_key, axis=1)

# Reuse coordinates already stored for the same location.
for key, group in df.groupby("_location_key"):
    valid = group[
        group["latitude"].notna()
        & group["longitude"].notna()
    ]

    if not valid.empty:
        lat = valid.iloc[0]["latitude"]
        lon = valid.iloc[0]["longitude"]

        missing_coords = (
            df["_location_key"].eq(key)
            & (df["latitude"].isna() | df["longitude"].isna())
        )

        df.loc[missing_coords, "latitude"] = lat
        df.loc[missing_coords, "longitude"] = lon
        df.loc[missing_coords, "geocode_status"] = "success"

geolocator = Nominatim(
    user_agent="fuel_route_assessment_v1",
    timeout=15
)

geocode_limited = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1.1,
    max_retries=1,
    error_wait_seconds=2,
    swallow_exceptions=True
)

def save_progress():
    # Do not save the temporary matching key.
    df.drop(columns=["_location_key"], errors="ignore").to_csv(
        CSV_PATH, index=False
    )

# Process only locations that have no coordinates and haven't
# already been marked not_found.
pending_mask = (
    df["latitude"].isna()
    & df["longitude"].isna()
    & ~df["geocode_status"].isin(["not_found"])
)

pending = df.loc[pending_mask].drop_duplicates(
    subset=["_location_key"]
).head(BATCH_SIZE)

print(f"Unique locations in this batch: {len(pending)}")

for idx, row in pending.iterrows():
    query = (
        f"{row['Address']}, {row['City']}, "
        f"{row['State']}, USA"
    )

    try:
        location = geocode_limited(query)

        if location:
            lat, lon = location.latitude, location.longitude

            same_location = df["_location_key"].eq(
                row["_location_key"]
            )

            df.loc[same_location, "latitude"] = lat
            df.loc[same_location, "longitude"] = lon
            df.loc[same_location, "geocode_status"] = "success"

            print(
                f"SUCCESS: {query} -> "
                f"({lat:.6f}, {lon:.6f})"
            )
        else:
            df.loc[
                df["_location_key"].eq(row["_location_key"]),
                "geocode_status"
            ] = "not_found"

            print(f"NOT FOUND: {query}")

    except Exception as exc:
        df.loc[
            df["_location_key"].eq(row["_location_key"]),
            "geocode_status"
        ] = "error"

        print(f"ERROR: {query}: {exc}")

    # Persist each lookup so progress survives interruptions.
    save_progress()

print("\nBatch saved to:", CSV_PATH)
print("Successful rows:", (df["geocode_status"] == "success").sum())
print("Not found:", (df["geocode_status"] == "not_found").sum())
print("Errors:", (df["geocode_status"] == "error").sum())
print(
    "Remaining rows without coordinates:",
    (df["latitude"].isna() | df["longitude"].isna()).sum()
)

df.drop(columns=["_location_key"], errors="ignore", inplace=True)

(8151, 10)
Unique locations in this batch: 200
NOT FOUND: I-75, EXIT 49, East Bernstadt, KY, USA
NOT FOUND: I-70, EXIT 3, Hancock, MD, USA
NOT FOUND: I-55,  EXIT 40, Marston, MO, USA
NOT FOUND: I-70, EXIT 359 & US-24, Limon, CO, USA
NOT FOUND: I-77, EXIT 100 & 101, Mount Airy, NC, USA
NOT FOUND: I-57/I-64, EXIT 95 & SR-15, Mount Vernon, IL, USA
NOT FOUND: I-30, EXIT 63 & SR-53, Gurdon, AR, USA
NOT FOUND: I-70 EXIT 121 & US-40, Columbia, MO, USA
SUCCESS: US-60, Norwood, MO, USA -> (37.110948, -92.452098)
NOT FOUND: I-12, EXIT 40 & US-51 BUS, Hammond, LA, USA
SUCCESS: US-30, Columbus, NE, USA -> (41.424305, -97.368212)
NOT FOUND: I-20, EXIT 71 & US-21, Columbia, SC, USA
NOT FOUND: I-10, EXIT 36 & SR-397, Lake Charles, LA, USA
SUCCESS: I-24, EXIT 16, Paducah, KY, USA -> (37.093960, -88.686735)
NOT FOUND: I-77, EXIT 111, North Canton, OH, USA
NOT FOUND: I-94, EXIT 147, Mandan, ND, USA
NOT FOUND: I-45 & FM 1603, EXIT 238, Rice, TX, USA
SUCCESS: US-84 & US-171, Mansfield, LA, USA -> (32.021830, -93.714349)
NOT FOUND: I-82, EXIT 36, Yakima, WA, USA
NOT FOUND: I-65/US-52, EXIT 140 & SR-32, Lebanon, IN, USA
NOT FOUND: I-10, EXIT 182 & SR-22, Sorrento, LA, USA
NOT FOUND: I-64, EXIT 43 & SR-395, Waddy, KY, USA
SUCCESS: US-59 & US-281, George West, TX, USA -> (28.331824, -98.117161)
NOT FOUND: I-90, EXIT 51 & I-291, Chicopee, MA, USA
NOT FOUND: I-40, EXIT 288 & SR-111, Cookeville, TN, USA
NOT FOUND: I-40, EXIT 24 & SR-209, Waynesville, NC, USA
NOT FOUND: I-90 EXIT 266 & CR-12, Dakota, MN, USA
NOT FOUND: I-57 & I-64, EXIT 95, Mount Vernon, IL, USA
NOT FOUND: I-20, EXIT 114 & US-441, Madison, GA, USA
NOT FOUND: CR-13, Kadoka, SD, USA
NOT FOUND: I-94, EXIT 30, Benton Harbor, MI, USA
SUCCESS: US-131 BUS, Big Rapids, MI, USA -> (43.705151, -85.484087)
SUCCESS: US-287, Dalhart, TX, USA -> (36.061609, -102.522223)
NOT FOUND: I-95, EXIT 41A & SR-175 & US-1, Jessup, MD, USA
NOT FOUND: I-94, EXIT 45 & CR-B, Menomonie, WI, USA
SUCCESS: SR-53 & SR-46, Marlette, MI, USA -> (43.326969, -83.080220)
NOT FOUND: I-75, EXIT 18, Monroe, MI, USA
NOT FOUND: I-75,  EXIT 2, Lake Park, GA, USA
NOT FOUND: I-69, EXIT 105 & SR-52, Perry, MI, USA
SUCCESS: I-94, EXIT 274, Port Huron, MI, USA -> (42.998240, -82.439685)
NOT FOUND: I-43, EXIT 107, Belgium, WI, USA
NOT FOUND: I-94, EXIT 12, Sawyer, MI, USA
NOT FOUND: I-80, EXIT 192 & SR-880, Loganton, PA, USA
NOT FOUND: I-85, EXIT 86, Linwood, NC, USA
NOT FOUND: I-90, EXIT 146, Alden, MN, USA
NOT FOUND: I-81, EXIT 72 & I-77, EXIT 41, Wytheville, VA, USA
NOT FOUND: I-5,  EXIT 278, Aurora, OR, USA
NOT FOUND: I-95, EXIT 8 & SR-88, Hardeeville, SC, USA
NOT FOUND: I-94, EXIT 115, Marshall, MI, USA
NOT FOUND: I-57,  EXIT 335, Monee, IL, USA
NOT FOUND: I-35, EXIT 59 & SR-21, Faribault, MN, USA
NOT FOUND: ST 14 BYPASS, Mankato, MN, USA
NOT FOUND: I-94, EXIT 38, Rothsay, MN, USA
NOT FOUND: I-94/US-52 EXIT 127 & US-71/SR-28, Sauk Centre, MN, USA
SUCCESS: CR-101, Shakopee, MN, USA -> (44.800250, -93.525678)
NOT FOUND: I-90, EXIT 233, Saint Charles, MN, USA
NOT FOUND: I-81,  EXIT 243 & US-11, Harrisonburg, VA, USA
NOT FOUND: I-295 EXIT 47A, Mount Holly, NJ, USA
NOT FOUND: I-55, EXIT 185 & US-67/US-61, Barnhart, MO, USA
NOT FOUND: I-94, EXIT 259 & SR- 89/CR-G, Lake Mills, WI, USA
NOT FOUND: I-90 EXIT 55, Rapid City, SD, USA
SUCCESS: US-59 & LOOP 151, Texarkana, TX, USA -> (33.398602, -94.086750)
NOT FOUND: I-64 EXIT 41, Okawville, IL, USA
NOT FOUND: I-10, EXIT 372, Ozona, TX, USA
NOT FOUND: I-29 EXIT 47 & SR-46, Beresford, SD, USA
NOT FOUND: SR-19, Perry, FL, USA
SUCCESS: I-10 & SR-182, EXIT 101, Lafayette, LA, USA -> (30.259167, -91.982790)
NOT FOUND: I-85/US-460, EXIT 63A & US-1/US-460 BUS, Petersburg, VA, USA
SUCCESS: US-360, Amelia Court House, VA, USA -> (37.358671, -77.958220)
NOT FOUND: I-80/US-30, EXIT 99 & US-191/SR-373, Rock Springs, WY, USA
NOT FOUND: I-30, EXIT 78 & SR-7, Arkadelphia, AR, USA
SUCCESS: US-70 & US-285, Roswell, NM, USA -> (33.394328, -104.522952)
SUCCESS: US-65 & US-36, Chillicothe, MO, USA -> (39.794875, -93.553278)
NOT FOUND: I-10, EXIT 465, Junction, TX, USA
NOT FOUND: I-55, I-74 & I-39 , EXIT 160, Bloomington, IL, USA
SUCCESS: US-54, Deerfield, MO, USA -> (37.837787, -94.517302)
NOT FOUND: I-129/US-20/US-75,  EXIT 2, South Sioux City, NE, USA
NOT FOUND: I-77, EXIT 14 & US-58/US-221, Hillsville, VA, USA
SUCCESS: US-61, Eolia, MO, USA -> (39.208842, -91.003512)
NOT FOUND: I-25, EXIT 240, Longmont, CO, USA
NOT FOUND: I-70/US-40, EXIT 252, Salina, KS, USA
NOT FOUND: I-75 EXIT 110, Mendon, OH, USA
SUCCESS: US-61 & CR MM, Hannibal, MO, USA -> (39.708250, -91.358741)
NOT FOUND: US-27/SR-25 & SR-826, Hialeah, FL, USA
NOT FOUND: I-35, EXIT 33, Holt, MO, USA
SUCCESS: US-54 & CR-HH, Fulton, MO, USA -> (38.846708, -91.947959)
NOT FOUND: I-80 & US-183, EXIT 257, Elm Creek, NE, USA
SUCCESS: US-23, Waverly, OH, USA -> (39.123995, -82.990071)
NOT FOUND: I-80, EXIT 263, Elm Creek, NE, USA
NOT FOUND: I-84, EXIT 353, Huntington, OR, USA
NOT FOUND: US-167/SR-25, Batesville, AR, USA
NOT FOUND: I-81,  EXIT 150, Troutville, VA, USA
NOT FOUND: I-10,  EXIT 4, Grand Bay, AL, USA
NOT FOUND: I-80/US-6, EXIT 284, Walcott, IA, USA
NOT FOUND: I-70 & GRAIN VALLEY RD EXIT 24, Grain Valley, MO, USA
SUCCESS: US-71, Nevada, MO, USA -> (37.846337, -94.335848)
NOT FOUND: I-96, EXIT 77, Portland, MI, USA
NOT FOUND: I-94, EXIT 167, Dexter, MI, USA
NOT FOUND: US-322/US-22 & SR-35, Mifflintown, PA, USA
NOT FOUND: I-10, EXIT 115 & SR-347, Breaux Bridge, LA, USA
NOT FOUND: I-24, EXIT 180B & US-27, Chattanooga, TN, USA
NOT FOUND: I-20, EXIT 205 & SR-46, Heflin, AL, USA
SUCCESS: US-65 & SR-J, Ozark, MO, USA -> (36.646782, -92.457520)
NOT FOUND: I-95/US-301, EXIT 33 & SR-602, Stony Creek, VA, USA
NOT FOUND: I-80, EXIT 29 & SR-8, Harrisville, PA, USA
NOT FOUND: I-90 & I-94, EXIT 108-A, Portage, WI, USA
NOT FOUND: I-55, EXIT 180, Pevely, MO, USA
NOT FOUND: I-41, EXIT 60 & SR-145, Richfield, WI, USA
NOT FOUND: I-87, EXIT 21B, West Coxsackie, NY, USA
NOT FOUND: I-40, EXIT 16 & US-40 BUS/US-66, Gallup, NM, USA
SUCCESS: US-2 /US-52, Minot, ND, USA -> (48.219776, -101.232994)
NOT FOUND: I-10 EXIT 37, El Paso, TX, USA
NOT FOUND: I-29/US-71, EXIT 18 & SR-92, Platte City, MO, USA
NOT FOUND: I-20, EXIT 479, Dallas, TX, USA
NOT FOUND: I-70, EXIT 66 & SR- 54, South Vienna, OH, USA
NOT FOUND: I-44 & SR-133, MM 145, Richland, MO, USA
NOT FOUND: I-70, EXIT 203, Foristell, MO, USA
SUCCESS: US-60/US-63, Cabool, MO, USA -> (37.123755, -92.091638)
NOT FOUND: I-10 & SR-347, EXIT 115, Breaux Bridge, LA, USA
NOT FOUND: I-80 & I-90 EXIT 71, Perrysburg, OH, USA
NOT FOUND: I-29, EXIT 144 & US-169, Saint Joseph, MO, USA
NOT FOUND: I-35, EXIT 471 & US-77, Denton, TX, USA
NOT FOUND: I-90, EXIT 34, North Bend, WA, USA
NOT FOUND: I-90/80-IN TOLL RD MM 22W, Portage, IN, USA
NOT FOUND: I-64, EXIT 94, Winchester, KY, USA
NOT FOUND: US-6/US-24/SR/CR-3, EXIT 41, Napoleon, OH, USA
NOT FOUND: I-40, EXIT 79, Milan, NM, USA
SUCCESS: US-71/US-136, Maryville, MO, USA -> (40.370730, -94.850475)
NOT FOUND: US-34, EXIT 258, West Burlington, IA, USA
NOT FOUND: I-95, EXIT 126 & US-17/US-1, Fredericksburg, VA, USA
SUCCESS: I-70, MID RIVERS MALL, Saint Peters, MO, USA -> (38.799043, -90.616080)
NOT FOUND: I-64, EXIT 28, Simpsonville, KY, USA
NOT FOUND: I-30 & US-270, EXIT 98A, Malvern, AR, USA
NOT FOUND: US-27/SR-25 & US-98/US-700/SR-700/SR-66, Sebring, FL, USA
SUCCESS: US-24, Taylor, MO, USA -> (39.936771, -91.512486)
NOT FOUND: I-35, EXIT 72 & US-19, Pauls Valley, OK, USA
NOT FOUND: I-35, EXIT 231 AND US-177, Braman, OK, USA
NOT FOUND: I-40 & I-75, EXIT 369, Knoxville, TN, USA
NOT FOUND: I-69C/US-281 & FM-2812, Edinburg, TX, USA
NOT FOUND: US-231/SR-75 & SR-20, Youngstown, FL, USA
NOT FOUND: I-80, EXIT 214, Rawlins, WY, USA
NOT FOUND: US-71/SR-60, Windom, MN, USA
NOT FOUND: I-10, EXIT 1, Ehrenberg, AZ, USA
SUCCESS: ST 6 EAST, Batesville, MS, USA -> (34.306986, -89.917429)
NOT FOUND: I-30/US-67, EXIT 68 & SR-205, Rockwall, TX, USA
SUCCESS: I-90 &  US-20, Hampshire, IL, USA -> (42.097803, -88.530364)
NOT FOUND: I-80, EXIT 229, Battle Mountain, NV, USA
NOT FOUND: I-64, EXIT 92, Leavenworth, IN, USA
NOT FOUND: I-10, EXIT 34-B, Gulfport, MS, USA
SUCCESS: US-20, Fort Dodge, IA, USA -> (42.485204, -94.205742)
NOT FOUND: I-75, EXIT 41 & SR-80, London, KY, USA
SUCCESS: US-84, Laurel, MS, USA -> (31.684279, -89.138369)
NOT FOUND: I-59, EXIT 97 & US-84, Laurel, MS, USA
SUCCESS: US-281 & SR-5, Dunseith, ND, USA -> (48.813057, -100.060968)
NOT FOUND: I-40 & CEMETARY RD, EXIT 26, Sayre, OK, USA
NOT FOUND: I-84, EXIT 265, La Grande, OR, USA
SUCCESS: US-49, Richland, MS, USA -> (32.276219, -90.175651)
NOT FOUND: I-35, EXIT 305, Mathis, TX, USA
NOT FOUND: I-29, EXIT 79 & US-159, Forest City, MO, USA
NOT FOUND: I-80, EXIT 4   4, Wendover, UT, USA
NOT FOUND: I-15, EXIT 164, Boulder, MT, USA
SUCCESS: I-196 & SR-40, EXIT 49, Holland, MI, USA -> (42.787602, -86.109083)
NOT FOUND: I-90, EXIT 426, Park City, MT, USA
NOT FOUND: I-90, EXIT 126 & SR-59, Gillette, WY, USA
NOT FOUND: I-29, EXIT 35, Faucett, MO, USA
NOT FOUND: I-35, EXIT 500, Gainesville, TX, USA
SUCCESS: US-395, Pasco, WA, USA -> (46.230169, -119.132777)
NOT FOUND: I-81,  EXIT 36, Greeneville, TN, USA
NOT FOUND: I-90, EXIT 330, Livingston, MT, USA
NOT FOUND: I-81, EXIT 5 W, Hagerstown, MD, USA
NOT FOUND: I-15 & US-2, EXIT 363, Shelby, MT, USA
NOT FOUND: I-90, EXIT 249, Whitehall, MT, USA
NOT FOUND: I-40, EXIT 198, Flagstaff, AZ, USA
NOT FOUND: I-97, EXIT 10, Millersville, MD, USA
SUCCESS: SR-16, Charlotte, NC, USA -> (35.227209, -80.843083)
NOT FOUND: I-85, EXIT 150, Haw River, NC, USA
NOT FOUND: I-95/SR-405,  EXIT 87 & US-17/SR-25, Richmond Hill, GA, USA
NOT FOUND: I-84, EXIT 304, Baker City, OR, USA
NOT FOUND: I-25, EXIT 254, Johnstown, CO, USA
NOT FOUND: I-95/SR-9, EXIT 147 & SR-60, Vero Beach, FL, USA
NOT FOUND: I-65, EXIT 215 & SR-114, Rensselaer, IN, USA
NOT FOUND: I-95,  EXIT 109B, Elkton, MD, USA
SUCCESS: US-41, Gurnee, IL, USA -> (42.376672, -87.901034)
NOT FOUND: I-65, EXIT 61, Franklin, TN, USA
NOT FOUND: I-40, EXIT 170 & US-601, Mocksville, NC, USA
NOT FOUND: I-29, EXIT 73, Sioux Falls, SD, USA
SUCCESS: US-77, Fremont, NE, USA -> (41.436135, -96.498463)
NOT FOUND: I-65, EXIT 304 & SR-69, Cullman, AL, USA
NOT FOUND: I-91, EXIT 24, Whately, MA, USA
NOT FOUND: I-29/US-81, EXIT 65 & I-94 BUS/US-10, Fargo, ND, USA
NOT FOUND: I-29, EXIT 64, Fargo, ND, USA
NOT FOUND: I-29, EXIT 141 & US-2, Grand Forks, ND, USA
SUCCESS: I-25, EXIT 128, Fountain, CO, USA -> (33.581176, -111.739198)
NOT FOUND: I-35 & ROUTE N, EXIT 106, Eagleville, MO, USA
NOT FOUND: I-94/US-52, EXIT 178 & SR-24, Clearwater, MN, USA
SUCCESS: US-2/US-52, Minot, ND, USA -> (48.219776, -101.232994)
NOT FOUND: I-10, EXIT 139, Grosse Tete, LA, USA
NOT FOUND: I-87, EXIT 32, Lewis, NY, USA
NOT FOUND: I-95, EXIT 68 & SR-61, Walterboro, SC, USA
NOT FOUND: I-78/US-22, EXIT 45 & SR-863, Kutztown, PA, USA

Batch saved to: ../data/fuel_prices.csv
Successful rows: 216
Not found: 986
Errors: 0
Remaining rows without coordinates: 7935

In [37]:
# Filter the DataFrame to keep only successful rows
df_success = df[df["geocode_status"] == "success"]
print(df_success.shape)
df_success.head()

(216, 10)

,OPIS Truckstop ID,Truckstop Name,Address,City,State,Rack ID,Retail Price,latitude,longitude,geocode_status
5,35,ACI TRUCK STOP,US-46,Columbia,NJ,90,3.079,40.927229,-75.088798,success
12,75,Good 2 Go #709,US-50,Montrose,CO,810,3.424,38.479856,-107.879058,success
13,77,OASIS TRAVEL PLAZA,US-13,Laurel,DE,243,3.229,38.571711,-75.563410,success
14,79,DELAWARE TRUCK PLAZA,US-13 & US-40,New Castle,DE,243,3.249,39.615985,-75.662956,success
26,127,CIRCLE K #4700095,US-41,Henderson,KY,340,3.609,37.904393,-87.550779,success

# PostgreSQL Database

In [42]:
import os
import pandas as pd
from sqlalchemy import create_engine, text
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# Database configuration
DB_NAME = os.getenv("DB_NAME", "strata_fuel_db")
DB_USER = os.getenv("DB_USER", "strata_fuel_user")
DB_PASSWORD = os.getenv("DB_PASSWORD", "StrataFuelEngine")
DB_HOST = os.getenv("DB_HOST", "127.0.0.1")
DB_PORT = os.getenv("DB_PORT", 5432)

TABLE_NAME = "fuel_stations"
BATCH_SIZE = 100

# Create PostgreSQL connection
DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

# Read all station records from PostgreSQL
with engine.connect() as conn:
    df = pd.read_sql(
        text(f'SELECT * FROM "{TABLE_NAME}"'),
        conn
    )

print("Data shape:", df.shape)
display(df.head())

# Validate required columns
required_columns = ["address", "city", "state"]
missing_columns = [col for col in required_columns if col not in df.columns]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

# Normalize location fields
for col in required_columns:
    df[col] = df[col].fillna("").astype(str).str.strip()

# Ensure coordinate and status columns exist in the DataFrame
for col in ["latitude", "longitude"]:
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = pd.to_numeric(df[col], errors="coerce")

if "geocode_status" not in df.columns:
    df["geocode_status"] = pd.NA

df["geocode_status"] = df["geocode_status"].astype("string")

# A normalized key identifies duplicate locations.
def make_location_key(row):
    return "|".join(
        str(row[col]).strip().casefold()
        for col in ["address", "city", "state"]
    )

df["_location_key"] = df.apply(make_location_key, axis=1)

# Reuse existing coordinates for duplicate locations.
for key, group in df.groupby("_location_key"):
    valid = group[
        group["latitude"].notna()
        & group["longitude"].notna()
    ]

    if not valid.empty:
        lat = valid.iloc[0]["latitude"]
        lon = valid.iloc[0]["longitude"]

        missing_coords = (
            df["_location_key"].eq(key)
            & (df["latitude"].isna() | df["longitude"].isna())
        )

        df.loc[missing_coords, "latitude"] = lat
        df.loc[missing_coords, "longitude"] = lon
        df.loc[missing_coords, "geocode_status"] = "success"

# Initialize geocoder with a conservative request rate.
geolocator = Nominatim(
    user_agent="fuel_route_assessment_v1",
    timeout=15
)

geocode_limited = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1.1,
    max_retries=1,
    error_wait_seconds=2,
    swallow_exceptions=True
)

# Identify the primary key used to update individual database records.
# Change this if your table uses a different primary-key column.
PRIMARY_KEY = "id"

if PRIMARY_KEY not in df.columns:
    raise ValueError(
        f"Primary key column '{PRIMARY_KEY}' not found. "
        f"Available columns: {df.columns.tolist()}. "
        "Set PRIMARY_KEY to your table's actual primary-key column."
    )

# Persist coordinates/status for all rows sharing a location.
def save_location_progress(location_key):
    matching_rows = df[df["_location_key"].eq(location_key)]

    with engine.begin() as conn:
        for _, record in matching_rows.iterrows():
            conn.execute(
                text(f"""
                    UPDATE "{TABLE_NAME}"
                    SET latitude = :latitude,
                        longitude = :longitude,
                        geocode_status = :geocode_status
                    WHERE "{PRIMARY_KEY}" = :record_id
                """),
                {
                    "latitude": (
                        None if pd.isna(record["latitude"])
                        else float(record["latitude"])
                    ),
                    "longitude": (
                        None if pd.isna(record["longitude"])
                        else float(record["longitude"])
                    ),
                    "geocode_status": (
                        None if pd.isna(record["geocode_status"])
                        else str(record["geocode_status"])
                    ),
                    "record_id": record[PRIMARY_KEY]
                }
            )

# Process only locations that need geocoding.
pending_mask = (
    (df["latitude"].isna() | df["longitude"].isna())
    & ~df["geocode_status"].isin(["not_found"])
)

pending = df.loc[pending_mask].drop_duplicates(
    subset=["_location_key"]
).head(BATCH_SIZE)

print(f"Unique locations in this batch: {len(pending)}")

for _, row in pending.iterrows():
    query = (
        f"{row['address']}, {row['city']}, "
        f"{row['state']}, USA"
    )
    location_key = row["_location_key"]

    try:
        location = geocode_limited(query)

        if location:
            lat, lon = location.latitude, location.longitude
            same_location = df["_location_key"].eq(location_key)

            df.loc[same_location, "latitude"] = lat
            df.loc[same_location, "longitude"] = lon
            df.loc[same_location, "geocode_status"] = "success"

            print(
                f"SUCCESS: {query} -> ({lat:.6f}, {lon:.6f})"
            )
        else:
            df.loc[
                df["_location_key"].eq(location_key),
                "geocode_status"
            ] = "not_found"

            print(f"NOT FOUND: {query}")

    except Exception as exc:
        df.loc[
            df["_location_key"].eq(location_key),
            "geocode_status"
        ] = "error"

        print(f"ERROR: {query}: {exc}")

    # Save each lookup to PostgreSQL immediately.
    save_location_progress(location_key)

print("\nBatch saved to PostgreSQL table:", TABLE_NAME)
print("Successful rows:", (df["geocode_status"] == "success").sum())
print("Not found:", (df["geocode_status"] == "not_found").sum())
print("Errors:", (df["geocode_status"] == "error").sum())
print(
    "Remaining rows without coordinates:",
    (df["latitude"].isna() | df["longitude"].isna()).sum()
)

# Clean up the temporary matching key.
df.drop(columns=["_location_key"], errors="ignore", inplace=True)

engine.dispose()

Data shape: (6967, 13)

,id,opis_truckstop_id,name,address,city,state,rack_id,retail_price,latitude,longitude,created_at,updated_at,geocode_status
0,1297,20011,CUBBYS #111,US-81,Norfolk,NE,470,3.20900,42.008814,-97.426517,2026-10-17 10:47:37.242791+00:00,2026-10-17 19:39:54.442328+00:00,success
1,4619,69875,LOVES TRAVEL STOP #680,US-81,Norfolk,NE,470,3.31567,42.008814,-97.426517,2026-10-17 10:47:37.372016+00:00,2026-10-17 19:39:54.618062+00:00,success
2,2640,65683,ALLSUPS CONVENIENCE STORE #2225,US-60,Friona,TX,585,2.99900,34.634288,-102.738575,2026-10-17 10:47:37.285262+00:00,2026-10-17 19:39:54.491297+00:00,success
3,1191,9340,LANCASTER TRAVEL PLAZA,US-30,Ronks,PA,208,3.89900,40.019717,-76.178888,2026-10-17 10:47:37.242614+00:00,2026-10-17 19:39:54.442170+00:00,success
4,1306,20036,SMOKIN JOES,I-90 EXIT 24,Sanborn,NY,38,3.69900,NaN,NaN,2026-10-17 10:47:37.242806+00:00,2026-10-17 19:39:54.442342+00:00,not_found

Unique locations in this batch: 100
SUCCESS: US-41, Little Chute, WI, USA -> (44.297891, -88.349677)
NOT FOUND: I-95, EXIT 89 & SR-802, Ashland, VA, USA
NOT FOUND: US-6/CR-74, Hastings, NE, USA
NOT FOUND: I-10, EXIT 37, El Paso, TX, USA
NOT FOUND: I-10, EXIT 68, Deming, NM, USA
NOT FOUND: US-20, EXIT 11 & SR-140, Shrewsbury, MA, USA
NOT FOUND: I-80, EXIT 237 & US-283, Lexington, NE, USA
NOT FOUND: I-25, EXIT 135, Douglas, WY, USA
NOT FOUND: I-80, EXIT 19 & SR-659, Sparks, NV, USA
NOT FOUND: I-30, EXIT 106, Malvern, AR, USA
NOT FOUND: I-70, EXIT 11 & CR-41, Valley Grove, WV, USA
SUCCESS: US- 22 & SR-322, Duncannon, PA, USA -> (40.393143, -77.032575)
NOT FOUND: I-77, EXIT 95 & SR-61, Charleston, WV, USA
NOT FOUND: I-70, EXIT 47, Palisade, CO, USA
SUCCESS: US-20 & US-83, Valentine, NE, USA -> (42.874675, -100.550616)
SUCCESS: US-275, Wisner, NE, USA -> (41.985189, -96.910465)
NOT FOUND: I-95, EXIT 3, Portsmouth, NH, USA
NOT FOUND: I-85, EXIT 42, Tuskegee, AL, USA
NOT FOUND: I-82, EXIT 1 & US-730, Umatilla, OR, USA
NOT FOUND: I-8I, EXIT 77, Harrisburg, PA, USA
NOT FOUND: I-84, EXIT 216 & SR 331,, Pendleton, OR, USA
NOT FOUND: SR-17MAHWA, Mahwah, NJ, USA
NOT FOUND: I-80 & US-189, EXIT 3, Evanston, WY, USA
NOT FOUND: I-80, EXIT 358 & I-25, EXIT 9 & US-30, Cheyenne, WY, USA
NOT FOUND: I-80, EXIT 68 & SR-374, Little America, WY, USA
NOT FOUND: I-84, EXIT 1, Montague, NJ, USA
SUCCESS: US-41, Fond Du Lac, WI, USA -> (43.745511, -88.453672)
NOT FOUND: I-94  EXIT 4 & US-12, Hudson, WI, USA
NOT FOUND: I-41, EXIT 57 & SR-167, Richfield, WI, USA
NOT FOUND: I-90/I-94, EXIT 132 & US-51, De Forest, WI, USA
NOT FOUND: I-90/I-94/I-39, EXIT 132 & US-51, De Forest, WI, USA
NOT FOUND: US-151, EXIT 26, Belmont, WI, USA
NOT FOUND: I-64, EXIT 39 & SR-34, Hurricane, WV, USA
NOT FOUND: I-5, EXIT 136B, SR-509, Tacoma, WA, USA
NOT FOUND: I-90, EXIT 109 & US-97, Ellensburg, WA, USA
NOT FOUND: I-5, EXIT 99, Tumwater, WA, USA
NOT FOUND: I-90, EXIT 286, Spokane, WA, USA
NOT FOUND: I-85, EXIT 4 & SR-93/SR-903, Bracey, VA, USA
NOT FOUND: I-95, EXIT 92 & SR-54, Ashland, VA, USA
NOT FOUND: I-264, EXIT 13B, Chesapeake, VA, USA
NOT FOUND: I-81 & I-64, EXIT 205, Raphine, VA, USA
NOT FOUND: I-80, EXIT 242, Coralville, IA, USA
NOT FOUND: I-15, EXIT 112, Beaver, UT, USA
NOT FOUND: I-80, EXIT 99, Tooele, UT, USA
SUCCESS: I-15 & I-80 SR 201, EXIT 305, Salt Lake City, UT, USA -> (40.785202, -111.990179)
NOT FOUND: I-40, EXIT 74, Amarillo, TX, USA
NOT FOUND: I-10, EXIT 138, Van Horn, TX, USA
SUCCESS: US-64, Farmington, NM, USA -> (36.716414, -108.152766)
SUCCESS: US-84 & US-180, Snyder, TX, USA -> (32.718080, -100.918231)
NOT FOUND: I-20, EXIT 242, Sweetwater, TX, USA
NOT FOUND: I-27, EXIT 1C, Lubbock, TX, USA
NOT FOUND: I-20, EXIT 177 & US-87, Big Spring, TX, USA
NOT FOUND: I-10, EXIT 25, El Paso, TX, USA
NOT FOUND: I-35,  EXIT 204, San Marcos, TX, USA
NOT FOUND: I-24, EXIT 62, Antioch, TN, USA
NOT FOUND: I-65, EXIT 22 & US-31 ALT/SR-11, Cornersville, TN, USA
NOT FOUND: I-40 & SR-138, EXIT 68, Denmark, TN, USA
NOT FOUND: I-40, EXIT 197, Moriarty, NM, USA
NOT FOUND: I-65, EXIT 6, Ardmore, TN, USA
SUCCESS: US-12 & US-281, Aberdeen, SD, USA -> (45.464981, -98.487813)
NOT FOUND: I-90, EXIT 192 & I-90 BUS/US-83, Murdo, SD, USA
NOT FOUND: I-90, EXIT 61, Rapid City, SD, USA
NOT FOUND: I-90 EXIT 399 & SR 115, Sioux Falls, SD, USA
NOT FOUND: I-95, EXIT 119, Manning, SC, USA
NOT FOUND: I-80, EXIT 42, Emlenton, PA, USA
NOT FOUND: I-80, EXIT 158, Milesburg, PA, USA
NOT FOUND: I-80, EXIT 232, Bloomsburg, PA, USA
NOT FOUND: I-80, EXIT 120, Clearfield, PA, USA
NOT FOUND: I-78, EXIT 10 (PA 645), Myerstown, PA, USA
NOT FOUND: I-80 EXIT 78, & SR-36, Brookville, PA, USA
NOT FOUND: I-76 & US30, EXIT 161, Breezewood, PA, USA
NOT FOUND: I-15, EXIT 12, Jean, NV, USA
NOT FOUND: I-81, EXIT 52 & I-76, EXIT 226, Carlisle, PA, USA
NOT FOUND: I-80, EXIT 173 & SR-64, Lamar, PA, USA
SUCCESS: I-5, EXIT 307, Portland, OR, USA -> (45.585536, -122.585820)
NOT FOUND: I-40, EXIT 142, Oklahoma City, OK, USA
NOT FOUND: I-70 & US-42, EXIT 79, London, OH, USA
NOT FOUND: I-80 & SR 46, EXIT 223, Youngstown, OH, USA
NOT FOUND: I-80, EXIT 234, Hubbard, OH, USA
NOT FOUND: SR-17, EXIT 66, Apalachin, NY, USA
NOT FOUND: I-70,  EXIT 10 & US-127, Eaton, OH, USA
NOT FOUND: I-90, EXIT 52E, Buffalo, NY, USA
NOT FOUND: I-90, EXIT 235 & SR-193, Kingsville, OH, USA
NOT FOUND: I-71, EXIT 65 & SR-435 & US-35, Jeffersonville, OH, USA
NOT FOUND: I-94, EXIT 260, Jamestown, ND, USA
NOT FOUND: I-94, EXIT 307, Tower City, ND, USA
NOT FOUND: I-26, EXIT 28, Saluda, NC, USA
NOT FOUND: I-90, EXIT 42, Phelps, NY, USA
NOT FOUND: I-85, EXIT 71, Salisbury, NC, USA
NOT FOUND: I-90 & RTE 22, EXIT B-3, Canaan, NY, USA
NOT FOUND: I-90, EXIT 58, Irving, NY, USA
NOT FOUND: SR-17, EXIT 63, Nichols, NY, USA
NOT FOUND: US-9W/SR-32, Glenmont, NY, USA
NOT FOUND: I-40/US-54, EXIT 277 & US-84, Santa Rosa, NM, USA
SUCCESS: US-60, Clovis, NM, USA -> (34.404576, -103.248496)
NOT FOUND: I-10, EXIT 139, Las Cruces, NM, USA
NOT FOUND: I-10, VADO EXIT 155, Vado, NM, USA
NOT FOUND: I-40, EXIT 159D & I-25/US-85, EXIT 227, Albuquerque, NM, USA
NOT FOUND: I-40, EXIT 16 & HWY 66, Gallup, NM, USA
NOT FOUND: I-10, EXIT 81, Deming, NM, USA

Batch saved to PostgreSQL table: fuel_stations
Successful rows: 225
Not found: 961
Errors: 0
Remaining rows without coordinates: 6742

# SQLite3 Database

In [44]:
import sqlite3
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

# SQLite database configuration
DB_PATH = "../db.sqlite3"
TABLE_NAME = "fuel_stations"
PRIMARY_KEY = "id"
BATCH_SIZE = 1000

# Connect to SQLite
conn = sqlite3.connect(DB_PATH)

# Read station records
df = pd.read_sql_query(
    f'SELECT * FROM "{TABLE_NAME}"',
    conn
)

print("Data shape:", df.shape)
display(df.head())

# Validate required columns
required_columns = ["address", "city", "state"]
missing_columns = [
    col for col in required_columns if col not in df.columns
]

if missing_columns:
    conn.close()
    raise ValueError(f"Missing required columns: {missing_columns}")

# Ensure coordinate columns exist in SQLite
existing_columns = {
    row[1]
    for row in conn.execute(f'PRAGMA table_info("{TABLE_NAME}")')
}

for col in ["latitude", "longitude", "geocode_status"]:
    if col not in existing_columns:
        column_type = (
            "REAL" if col in ["latitude", "longitude"]
            else "TEXT"
        )
        conn.execute(
            f'ALTER TABLE "{TABLE_NAME}" '
            f'ADD COLUMN "{col}" {column_type}'
        )

conn.commit()

# Normalize location fields
for col in required_columns:
    df[col] = df[col].fillna("").astype(str).str.strip()

for col in ["latitude", "longitude"]:
    if col not in df.columns:
        df[col] = pd.NA
    df[col] = pd.to_numeric(df[col], errors="coerce")

if "geocode_status" not in df.columns:
    df["geocode_status"] = pd.NA

df["geocode_status"] = df["geocode_status"].astype("string")

# Verify the primary key
if PRIMARY_KEY not in df.columns:
    conn.close()
    raise ValueError(
        f"Primary key '{PRIMARY_KEY}' not found. "
        f"Available columns: {df.columns.tolist()}. "
        "Change PRIMARY_KEY to the actual unique key."
    )

if df[PRIMARY_KEY].isna().any() or df[PRIMARY_KEY].duplicated().any():
    conn.close()
    raise ValueError(
        f"'{PRIMARY_KEY}' must uniquely identify every database row."
    )

# Build normalized keys for duplicate locations
def make_location_key(row):
    return "|".join(
        str(row[col]).strip().casefold()
        for col in ["address", "city", "state"]
    )

df["_location_key"] = df.apply(make_location_key, axis=1)

# Reuse coordinates already available for duplicate locations
for key, group in df.groupby("_location_key"):
    valid = group[
        group["latitude"].notna()
        & group["longitude"].notna()
    ]

    if not valid.empty:
        lat = valid.iloc[0]["latitude"]
        lon = valid.iloc[0]["longitude"]

        missing_coords = (
            df["_location_key"].eq(key)
            & (df["latitude"].isna() | df["longitude"].isna())
        )

        df.loc[missing_coords, "latitude"] = lat
        df.loc[missing_coords, "longitude"] = lon
        df.loc[missing_coords, "geocode_status"] = "success"

# Geocoder
geolocator = Nominatim(
    user_agent="fuel_route_assessment_v1",
    timeout=15
)

geocode_limited = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1.1,
    max_retries=1,
    error_wait_seconds=2,
    swallow_exceptions=True
)

# Save all rows matching a location key
def save_location_progress(location_key):
    matching_rows = df[df["_location_key"].eq(location_key)]

    try:
        with conn:
            for _, record in matching_rows.iterrows():
                conn.execute(
                    f"""
                    UPDATE "{TABLE_NAME}"
                    SET latitude = ?,
                        longitude = ?,
                        geocode_status = ?
                    WHERE "{PRIMARY_KEY}" = ?
                    """,
                    (
                        None if pd.isna(record["latitude"])
                        else float(record["latitude"]),
                        None if pd.isna(record["longitude"])
                        else float(record["longitude"]),
                        None if pd.isna(record["geocode_status"])
                        else str(record["geocode_status"]),
                        record[PRIMARY_KEY]
                    )
                )
    except Exception:
        raise

# Select locations that need geocoding
pending_mask = (
    (df["latitude"].isna() | df["longitude"].isna())
    & ~df["geocode_status"].isin(["not_found"])
)

pending = df.loc[pending_mask].drop_duplicates(
    subset=["_location_key"]
).head(BATCH_SIZE)

print(f"Unique locations in this batch: {len(pending)}")

for _, row in pending.iterrows():
    query = (
        f"{row['address']}, {row['city']}, "
        f"{row['state']}, USA"
    )
    location_key = row["_location_key"]
    same_location = df["_location_key"].eq(location_key)

    try:
        location = geocode_limited(query)

        if location:
            lat, lon = location.latitude, location.longitude

            df.loc[same_location, "latitude"] = lat
            df.loc[same_location, "longitude"] = lon
            df.loc[same_location, "geocode_status"] = "success"

            print(
                f"SUCCESS: {query} -> ({lat:.6f}, {lon:.6f})"
            )
        else:
            df.loc[same_location, "geocode_status"] = "not_found"
            print(f"NOT FOUND: {query}")

    except Exception as exc:
        df.loc[same_location, "geocode_status"] = "error"
        print(f"ERROR: {query}: {exc}")

    # Persist every lookup immediately
    save_location_progress(location_key)

print("\nBatch saved to SQLite table:", TABLE_NAME)
print("Successful rows:", (df["geocode_status"] == "success").sum())
print("Not found:", (df["geocode_status"] == "not_found").sum())
print("Errors:", (df["geocode_status"] == "error").sum())
print(
    "Remaining rows without coordinates:",
    (df["latitude"].isna() | df["longitude"].isna()).sum()
)

# Remove the temporary key and close the database connection
df.drop(columns=["_location_key"], errors="ignore", inplace=True)
conn.close()

Data shape: (6967, 13)

,id,opis_truckstop_id,name,address,city,state,rack_id,retail_price,latitude,longitude,created_at,updated_at,geocode_status
0,1,7,WOODSHED OF BIG CABIN,"I-44, EXIT 283 & US-69",Big Cabin,OK,307,3.00733,NaN,NaN,2026-10-17 10:47:37.187000,2026-10-17 19:39:54.370000,not_found
1,2,9,KWIK TRIP #796,"I-94, EXIT 143 & US-12 & SR-21",Tomah,WI,420,3.28733,NaN,NaN,2026-10-17 10:47:37.187000,2026-10-17 19:39:54.370000,not_found
2,3,20,PILOT TRAVEL CENTER #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.89900,NaN,NaN,2026-10-17 10:47:37.187000,2026-10-17 19:39:54.370000,not_found
3,4,20,PILOT #1243,"I-8, EXIT 119 & SR-85",Gila Bend,AZ,930,3.89900,NaN,NaN,2026-10-17 10:47:37.187000,2026-10-17 19:39:54.370000,not_found
4,5,28,LITTLEFIELD EXPRESS #2,"I-540, EXIT 12 & US-71",Fort Smith,AR,645,3.39900,NaN,NaN,2026-10-17 10:47:37.187000,2026-10-17 19:39:54.370000,not_found

Unique locations in this batch: 1000
NOT FOUND: I-80, EXIT 440 & SR-50, EXIT 440, Omaha, NE, USA
NOT FOUND: I-80, EXIT 312 & US-281/US-34, Grand Island, NE, USA
NOT FOUND: I-87, EXIT 17N & US-9, Fort Edward, NY, USA
NOT FOUND: I-90, EXIT 96 & US-93/SR-200, Missoula, MT, USA
NOT FOUND: SR-17, EXIT 20, Salamanca, NY, USA
NOT FOUND: I-90, EXIT 96 & US-93, Missoula, MT, USA
NOT FOUND: I-90, EXIT 437, Laurel, MT, USA
NOT FOUND: I-44, EXIT 88 & SR-125, Strafford, MO, USA
NOT FOUND: I-70, EXIT 28, Oak Grove, MO, USA
NOT FOUND: I-55, EXIT 58 & SR-80, Matthews, MO, USA
NOT FOUND: I-70, EXIT 148 & US-54, Kingdom City, MO, USA
NOT FOUND: I-44, EXIT 127, Lebanon, MO, USA
NOT FOUND: I-55, EXIT 220, Tillatoba, MS, USA
NOT FOUND: I-70, EXIT 208, Belmont, OH, USA
NOT FOUND: I-20 & I-59, EXIT 160, Meridian, MS, USA
NOT FOUND: I-94/US-52, EXIT 127 & US-71, Sauk Centre, MN, USA
SUCCESS: I-35 & I-90, EXIT 11, Albert Lea, MN, USA -> (43.648013, -93.368266)
NOT FOUND: I-69,EXIT 25 & SR-60, Tekonsha, MI, USA
SUCCESS: US-52 & SR-234, Ironton, OH, USA -> (38.536747, -82.682941)
NOT FOUND: I-75, EXIT 32A, Trenton, MI, USA
NOT FOUND: I-94, EXIT 104, Battle Creek, MI, USA
NOT FOUND: I-495, EXIT 14A & US-1, Wrentham, MA, USA
SUCCESS: US-1, Peabody, MA, USA -> (42.522528, -70.996747)
NOT FOUND: I-95, EXIT 44, Bangor, ME, USA
NOT FOUND: I-95, EXIT 2, Kittery, ME, USA
NOT FOUND: I-10, EXIT 266 & US-190, Slidell, LA, USA
SUCCESS: ST 103, Port Barre, LA, USA -> (30.547350, -91.964560)
NOT FOUND: I-80, EXIT 226, Girard, OH, USA
NOT FOUND: I-65, EXIT 38 & SR-101, Smiths Grove, KY, USA
NOT FOUND: I-65, EXIT 81 & SR-84, Sonora, KY, USA
NOT FOUND: I-75/I-71, EXIT 175 & SR-338, Walton, KY, USA
NOT FOUND: I-65, EXIT 2 & US-31W, Franklin, KY, USA
NOT FOUND: I-75, EXIT 181, Florence, KY, USA
NOT FOUND: I-70/US-40, EXIT 127 & US-283, Wakeeney, KS, USA
NOT FOUND: I-70, EXIT 76 & US-40/US-83, Oakley, KS, USA
NOT FOUND: I-77, EXIT 1 & SR-7, Marietta, OH, USA
SUCCESS: US-20/SR-18, Monroeville, OH, USA -> (41.246408, -82.697621)
NOT FOUND: I-80, EXIT 142 & US-65, Altoona, IA, USA
NOT FOUND: I-75, EXIT 168, North Baltimore, OH, USA
NOT FOUND: I-29, EXIT 143, Sioux City, IA, USA
NOT FOUND: I-80, EXIT 284, Walcott, IA, USA
NOT FOUND: US-224 & SR-61/SR-598, Willard, OH, USA
NOT FOUND: I-35 & I-80, EXIT 126, Urbandale, IA, USA
NOT FOUND: I-69, EXIT 245 & SR-28, Gaston, IN, USA
SUCCESS: US-30 & SR-23, Grovertown, IN, USA -> (41.375043, -86.504734)
SUCCESS: US-31 & US-24, Peru, IN, USA -> (40.753725, -86.069033)
NOT FOUND: I-70, EXIT 137 AT MILE 137, Cambridge City, IN, USA
NOT FOUND: I-70,  EXIT 23, Brazil, IN, USA
NOT FOUND: I-70, EXIT 59 & SR-39, Clayton, IN, USA
NOT FOUND: I-65, EXIT 201 & US-231/US-24, Remington, IN, USA
NOT FOUND: I-65/US-52, EXIT 130, Whitestown, IN, USA
NOT FOUND: I-74,  EXIT 143, Greensburg, IN, USA
NOT FOUND: I-57 & I-70, EXIT 160, Effingham, IL, USA
NOT FOUND: I-80, EXIT 112 & SR-47, Morris, IL, USA
NOT FOUND: I-57, EXIT 54B & SR-13, Marion, IL, USA
NOT FOUND: I-70/I-55, EXIT 4 & SR-203, East Saint Louis, IL, USA
NOT FOUND: I-55, EXIT 145 & US-136, Mc Lean, IL, USA
NOT FOUND: I-84, EXIT 54, Boise, ID, USA
NOT FOUND: I-85, EXIT 70, Cusseta, AL, USA
NOT FOUND: I-75, EXIT 237, SR-331 & US-41, Forest Park, GA, USA
NOT FOUND: I-75, EXIT 306 & SR-140, Adairsville, GA, USA
NOT FOUND: I-85 & SR-219, EXIT 13, Lagrange, GA, USA
NOT FOUND: I-75, EXIT 181, Pinconning, MI, USA
NOT FOUND: I-10, EXIT 343 & US-301, Jacksonville, FL, USA
NOT FOUND: I-4/SR-400, EXIT 7 & US-301/SR-41, Tampa, FL, USA
NOT FOUND: I-95, EXIT 56, Branford, CT, USA
NOT FOUND: I-95, EXIT 40, Milford, CT, USA
NOT FOUND: I-95, EXIT 93 & SR-216, North Stonington, CT, USA
NOT FOUND: I-70, EXIT 266, Wheat Ridge, CO, USA
NOT FOUND: I-76, EXIT 90B & SR-71, Brush, CO, USA
NOT FOUND: I-40, EXIT 108 & US-66/US-281 BUS, Calumet, OK, USA
NOT FOUND: I-44, EXIT 83, Chickasha, OK, USA
NOT FOUND: I-40, EXIT 292, Holbrook, AZ, USA
NOT FOUND: I-10, EXIT 268, Tucson, AZ, USA
SUCCESS: US-75, Copan, OK, USA -> (36.897579, -95.926093)
NOT FOUND: I-10, EXIT 340, Willcox, AZ, USA
NOT FOUND: I-40, EXIT 71, Clinton, OK, USA
NOT FOUND: I-35, EXIT 55, Davis, OK, USA
NOT FOUND: US-72/SR-20/SR-157 & CR-59, Tuscumbia, AL, USA
NOT FOUND: I-65, EXIT 168 & US-80/US-82/SR-6/SR-8, Montgomery, AL, USA
NOT FOUND: I-20 & I-59, EXIT 76, Tuscaloosa, AL, USA
NOT FOUND: I-40 EXIT 7 & SR 30, Erick, OK, USA
NOT FOUND: I-40, EXIT 53, Kingman, AZ, USA
NOT FOUND: I-75, EXIT 139, Fort Myers, FL, USA
NOT FOUND: I-44, EXIT 251, Villa Ridge, MO, USA
NOT FOUND: I-70, EXIT 188, Warrenton, MO, USA
NOT FOUND: ST 16, EXIT 213, Glendive, MT, USA
NOT FOUND: I-80, EXIT 353 & US-81, York, NE, USA
SUCCESS: US-6 & US-23, Bradner, OH, USA -> (41.324219, -83.438539)
SUCCESS: US-30 & SR-94, Dalton, OH, USA -> (40.799162, -81.695387)
NOT FOUND: I-40, EXIT 76, Amarillo, TX, USA
NOT FOUND: I-27, EXIT 74, Tulia, TX, USA
SUCCESS: SR-351, Muskogee, OK, USA -> (35.749315, -95.361374)
NOT FOUND: I-25, EXIT 7, Cheyenne, WY, USA
NOT FOUND: I-25/US-87, EXIT 9 & I-80, EXIT 359C & I-80 BUS/US-30, Cheyenne, WY, USA
NOT FOUND: I-75/SR-401, EXIT 201 & SR-36, Jackson, GA, USA
NOT FOUND: I-95, EXIT 7, Woodbine, GA, USA
NOT FOUND: I-65, EXIT 121, Shepherdsville, KY, USA
NOT FOUND: US-52/SR-55, & 117TH ST, MM300, Inver Grove Heights, MN, USA
SUCCESS: US-60, US-70 & US-84, Texico, NM, USA -> (34.389532, -103.044293)
NOT FOUND: I-80, EXIT 280 & SR- 278, Carlin, NV, USA
NOT FOUND: I-70, EXIT 156B & US-40, New Paris, OH, USA
NOT FOUND: I-24, EXIT 114 & US-41, Manchester, TN, USA
NOT FOUND: I-90/I-39, EXIT 158 & I-43/SR-81, EXIT 1, Beloit, WI, USA
NOT FOUND: I-25/US-87, EXIT 7 & US-212, Cheyenne, WY, USA
NOT FOUND: I-35, EXIT 120, Oklahoma City, OK, USA
NOT FOUND: I-35, EXIT 72  & SR-19, Pauls Valley, OK, USA
NOT FOUND: I-40, EXIT 200, Seminole, OK, USA
SUCCESS: US-220 & CR-902, Ridgeway, VA, USA -> (36.576805, -79.858372)
NOT FOUND: I-15, EXIT 222, Nephi, UT, USA
NOT FOUND: I-20, EXIT 42 & US-285, Pecos, TX, USA
NOT FOUND: I-44, EXIT 20, Walters, OK, USA
NOT FOUND: I-40, EXIT 287 & SR-100, Webbers Falls, OK, USA
NOT FOUND: I-80, EXIT 300 & SR-40D, Wood River, NE, USA
SUCCESS: I-78/US-22, Allentown, PA, USA -> (40.613814, -75.469115)
SUCCESS: US-2 & SR-4, Farmington, ME, USA -> (44.670628, -70.151454)
NOT FOUND: SR-309, Coopersburg, PA, USA
NOT FOUND: I-76,  EXIT 23/312, Elverson, PA, USA
NOT FOUND: I-84, EXIT 20 & SR-507, Greentown, PA, USA
NOT FOUND: I-81, EXIT 217 & SR-547, Harford, PA, USA
NOT FOUND: I-79, EXIT 1, Mount Morris, PA, USA
NOT FOUND: I-95, EXIT 181, Latta, SC, USA
NOT FOUND: I-81, EXIT 199, Dalton, PA, USA
NOT FOUND: I-70, EXIT 10 & SR-127, Eaton, OH, USA
NOT FOUND: I-75,  EXIT 167, North Baltimore, OH, USA
NOT FOUND: I-78, EXIT 7 & SR-173, Bloomsbury, NJ, USA
NOT FOUND: I-76, EXIT 24A/326, Wayne, PA, USA
NOT FOUND: I-70, EXIT 148, Kingdom City, MO, USA
NOT FOUND: I-26, EXIT 115 & US-321, West Columbia, SC, USA
NOT FOUND: I-35, EXIT 155 & US-75, Lebo, KS, USA
NOT FOUND: I-94, EXIT 22B & US-20, Chesterton, IN, USA
NOT FOUND: I-85, EXIT 83 & SR-110, Cowpens, SC, USA
NOT FOUND: I-20, EXIT 26, Villa Rica, GA, USA
NOT FOUND: I-20, EXIT 5 & US-25, North Augusta, SC, USA
NOT FOUND: I-77, EXIT 65 & SR-9, Richburg, SC, USA
NOT FOUND: I-64, EXIT 39 & SR-34, Teays, WV, USA
NOT FOUND: I-26, EXIT 104, Columbia, SC, USA
NOT FOUND: I-90/I-94, EXIT 69 & SR-82, Mauston, WI, USA
NOT FOUND: I-90 & 94 EXIT 79, Lyndon Station, WI, USA
SUCCESS: US-85 & US-34, Belle Fourche, SD, USA -> (44.673133, -103.851734)
NOT FOUND: I-90, EXIT 284 & SR-45, Kimball, SD, USA
SUCCESS: US-75, Anna, TX, USA -> (33.364125, -96.583295)
NOT FOUND: I-95, EXIT 170 & SR-327, Florence, SC, USA
NOT FOUND: I-90, EXIT 310 & SR-281, Plankinton, SD, USA
NOT FOUND: I-75 & I-40, EXIT 369, Knoxville, TN, USA
NOT FOUND: US-30/US-62 & SR-297, Canton, OH, USA
NOT FOUND: I-90, EXIT 223 & SR-45, Austinburg, OH, USA
NOT FOUND: I-40 & I-85, EXIT 138 & SR-61, Whitsett, NC, USA
NOT FOUND: I-29, EXIT 26 & SR-50, Burbank, SD, USA
NOT FOUND: I-90, EXIT 212 & SR-83, Vivian, SD, USA
NOT FOUND: I-81,  EXIT 34, Parish, NY, USA
NOT FOUND: I-80, EXIT 151, Imlay, NV, USA
SUCCESS: SR-759, Saint Joseph, MO, USA -> (39.730101, -94.812654)
NOT FOUND: I-55, EXIT 144, Pickens, MS, USA
NOT FOUND: I-95, EXIT 157, Newport, ME, USA
NOT FOUND: I-24, EXIT 64, La Vergne, TN, USA
SUCCESS: US-59 & US-54, Moran, KS, USA -> (37.916147, -95.170255)
NOT FOUND: I-70, EXIT 341, Maple Hill, KS, USA
NOT FOUND: US-151/US-52/US-61, Dubuque, IA, USA
NOT FOUND: I-65, EXIT 95, Whiteland, IN, USA
SUCCESS: US-31, Rochester, IN, USA -> (41.070716, -86.215768)
NOT FOUND: I-80, EXIT 6, Gary, IN, USA
NOT FOUND: I-95, EXIT 173, Palm Bay, FL, USA
NOT FOUND: I-10, EXIT 208-A, Eloy, AZ, USA
NOT FOUND: I-85/US-29, EXIT 62 & US-280/US-431/SR-38/SR-1, Opelika, AL, USA
NOT FOUND: I-95, EXIT 104, Ruther Glen, VA, USA
NOT FOUND: I-45, EXIT 179, Mcallen, TX, USA
NOT FOUND: I-390 & COMMERCE, EXIT 5, Dansville, NY, USA
NOT FOUND: I-287, EXIT 66, Mahwah, NJ, USA
SUCCESS: US-45 & US-64, Selmer, TN, USA -> (35.170074, -88.592365)
NOT FOUND: I-35 & I-80, EXIT 125 & US-6, Clive, IA, USA
NOT FOUND: I-20, EXIT 11 & US-27/SR-1, Bremen, GA, USA
SUCCESS: US-50 & US-77, Florence, KS, USA -> (38.244462, -96.928079)
SUCCESS: SR-307, Savannah, GA, USA -> (32.079007, -81.092134)
NOT FOUND: I-40, EXIT 212, Nashville, TN, USA
NOT FOUND: I-65 & I-24, EXIT 87, Nashville, TN, USA
NOT FOUND: US-4, EXIT 2 & SR-22A, Fair Haven, VT, USA
SUCCESS: US-6 & US-50, Wellington, UT, USA -> (39.542466, -110.735434)
SUCCESS: US-35, Winamac, IN, USA -> (41.059205, -86.604608)
NOT FOUND: I-77 EXIT 58 & SR-666 & US-52, Bastian, VA, USA
NOT FOUND: I-95, EXIT 133 & US-17 BUS, Fredericksburg, VA, USA
NOT FOUND: I-15, EXIT 339, Conrad, MT, USA
NOT FOUND: I-39/US-51, EXIT 72 & US-34, Mendota, IL, USA
NOT FOUND: I-465, EXIT 4, Indianapolis, IN, USA
NOT FOUND: US-431/SR-1 & SR-27, Abbeville, AL, USA
SUCCESS: US-71/US-59, Ashdown, AR, USA -> (33.680915, -94.135377)
NOT FOUND: I-55, EXIT 4 & I-40, EXIT 280, West Memphis, AR, USA
NOT FOUND: I-8, EXIT 115 & SR-86, El Centro, CA, USA
NOT FOUND: I-20, EXIT 194, Augusta, GA, USA
NOT FOUND: I-85/SR-403, EXIT 41 & US-27 ALT, Newnan, GA, USA
NOT FOUND: US-30, EXIT 185 & SR-14, Marshalltown, IA, USA
NOT FOUND: I-84, EXIT 36, Nampa, ID, USA
NOT FOUND: I-39/US-51, EXIT 99 & SR-38, Rochelle, IL, USA
NOT FOUND: I-80 & I-94, EXIT 9A, Gary, IN, USA
NOT FOUND: I-65, EXIT 16 & MEMPHIS RD, Memphis, IN, USA
NOT FOUND: US-54/SR-7 & US-69, Fort Scott, KS, USA
NOT FOUND: I-35, EXIT 60, Mcpherson, KS, USA
NOT FOUND: I-24 & US-305, EXIT 3, Paducah, KY, USA
NOT FOUND: I-75, EXIT 11 & SR-92, Williamsburg, KY, USA
NOT FOUND: I-12, EXIT 40, Hammond, LA, USA
NOT FOUND: I-49, EXIT 23 & US-167, Opelousas, LA, USA
NOT FOUND: US-131, EXIT 72, Byron Center, MI, USA
NOT FOUND: I-69, EXIT 87, Dewitt, MI, USA
SUCCESS: I-94, EXIT 145, Jackson, MI, USA -> (39.070740, -94.603070)
NOT FOUND: I-75, EXIT 151 & SR- 81, Saginaw, MI, USA
NOT FOUND: I-55 EXIT 178, Herculaneum, MO, USA
NOT FOUND: I-55, EXIT 243 & US-278/SR-6, Batesville, MS, USA
NOT FOUND: I-55, EXIT 78, Natchez, MS, USA
NOT FOUND: I-95, EXIT 105, Kenly, NC, USA
NOT FOUND: I-77, EXIT 42, Troutman, NC, USA
SUCCESS: US-52, Kenmare, ND, USA -> (48.647058, -102.039813)
NOT FOUND: I-80, EXIT 432, Gretna, NE, USA
SUCCESS: I-89, EXIT 16, Enfield, NH, USA -> (43.568363, -72.151096)
NOT FOUND: I-295, EXIT 2C & SR-140, Penns Grove, NJ, USA
NOT FOUND: I-10 & AIRPORT RD, EXIT 132, Las Cruces, NM, USA
NOT FOUND: I-40, EXIT 333, Tucumcari, NM, USA
NOT FOUND: I-15, EXIT 46, North Las Vegas, NV, USA
NOT FOUND: I-80, EXIT 176, Winnemucca, NV, USA
NOT FOUND: I-86 & SR-17, EXIT 37, Bath, NY, USA
SUCCESS: SR-2 & SR-53, Port Clinton, OH, USA -> (41.511995, -82.937692)
NOT FOUND: I-44, EXIT 45 & SR-49, Lawton, OK, USA
NOT FOUND: I-35, EXIT 106 & SR-9 W, Norman, OK, USA
NOT FOUND: I-84, EXIT 261, La Grande, OR, USA
NOT FOUND: I-80, EXIT 256 & SR-93, Drums, PA, USA
NOT FOUND: I-90, EXIT 45 & US-20, North East, PA, USA
NOT FOUND: I-84, EXIT 26 & SR-390, Tafton, PA, USA
NOT FOUND: I-40, EXIT 188, Kingston Springs, TN, USA
NOT FOUND: US-287/US-81 & CR-1595, Alvord, TX, USA
NOT FOUND: I-10, EXIT 0, Anthony, TX, USA
NOT FOUND: I-30, EXIT 146 & US-37, Mount Vernon, TX, USA
NOT FOUND: I-37, EXIT 125, Elmendorf, TX, USA
NOT FOUND: I-94, EXIT 116 & SR-54, Black River Falls, WI, USA
SUCCESS: US-10 & SR-110, Fremont, WI, USA -> (44.271989, -88.850511)
NOT FOUND: I-77/I-64, EXIT 44 & SR-3, Beckley, WV, USA
NOT FOUND: HIGHWAY 2, EXIT 251, Calgary, AB, USA
NOT FOUND: I-69, EXIT 184 & SR-19, Memphis, MI, USA
NOT FOUND: I-5, EXIT 27, Kalama, WA, USA
NOT FOUND: I-10, EXIT 13 & CR-30, Theodore, AL, USA
SUCCESS: US-63 & US-167, El Dorado, AR, USA -> (33.211509, -92.665014)
NOT FOUND: I-75, EXIT 49, Lake Panasoffkee, FL, USA
NOT FOUND: I-285, EXIT 12, Atlanta, GA, USA
SUCCESS: US-1 & US-301, Folkston, GA, USA -> (30.830582, -82.009785)
SUCCESS: US-31 & SR-18, Kokomo, IN, USA -> (40.486444, -86.133635)
NOT FOUND: I-70, EXIT 184, Russell, KS, USA
NOT FOUND: I-64, EXIT 265, Mayfield, KY, USA
SUCCESS: US-84 & SR-28, Jonesville, LA, USA -> (31.626142, -91.813587)
NOT FOUND: I-49, EXIT 138 & SR-6, Natchitoches, LA, USA
NOT FOUND: I-75, EXIT 126, Mount Morris, MI, USA
SUCCESS: US-45 & US-72, Corinth, MS, USA -> (34.934360, -88.522335)
SUCCESS: SR-1, Saltillo, MS, USA -> (34.376590, -88.684461)
NOT FOUND: I-90, EXIT 455, Billings, MT, USA
NOT FOUND: I-85,  EXIT 71, Salisbury, NC, USA
NOT FOUND: SR-149, Fort Ann, NY, USA
NOT FOUND: I-40 EXIT 238, Lebanon, TN, USA
NOT FOUND: I-82, EXIT 69, Sunnyside, WA, USA
NOT FOUND: I-94 & BAKER RD, EXIT 167, Dexter, MI, USA
NOT FOUND: I-75, EXIT 328, Dalton, GA, USA
NOT FOUND: I-465/I-74/US-52/US-40/SR-67, EXIT 4 & SR-37, Indianapolis, IN, USA
NOT FOUND: I-25, EXIT 185 & SR-258, Casper, WY, USA
NOT FOUND: I-90, EXIT 27 & SR-97, Erie, PA, USA
NOT FOUND: I-80 , EXIT 310, Laramie, WY, USA
NOT FOUND: I-94 & RUSSELL RD, EXIT 1, Wadsworth, IL, USA
NOT FOUND: I-84, EXIT 28 & US-65, Milldale, CT, USA
NOT FOUND: I-75, EXIT 296, Cartersville, GA, USA
NOT FOUND: I-80, EXIT 209, Rawlins, WY, USA
NOT FOUND: I-20, EXIT 472, Dallas, TX, USA
NOT FOUND: I-10, EXIT 873 & SR-62, Orange, TX, USA
NOT FOUND: I-15 & I-84, EXIT 344 SR-39, Ogden, UT, USA
NOT FOUND: US-80, EXIT 3, Yuma, AZ, USA
NOT FOUND: I-80, EXIT 310, Laramie, WY, USA
SUCCESS: US-60, Globe, AZ, USA -> (33.394941, -110.775696)
NOT FOUND: I-75, EXIT 60, Tifton, GA, USA
NOT FOUND: I-25/US-85/US-87, EXIT 161 & SR-105, Monument, CO, USA
NOT FOUND: I-84 EXIT 1, Sturbridge, MA, USA
NOT FOUND: I-55, EXIT 267 & SR-53, Bolingbrook, IL, USA
SUCCESS: US-84 & SR-21, Monroeville, AL, USA -> (31.527822, -87.324633)
NOT FOUND: US-25/SR-121/SR-23/SR-67, Millen, GA, USA
NOT FOUND: I-65, EXIT 20, Bowling Green, KY, USA
NOT FOUND: I-10, EXIT 151 & SR-415, Port Allen, LA, USA
NOT FOUND: I-10, EXIT 4, Vinton, LA, USA
NOT FOUND: SR-60 & SR-30/SR-4, Saint James, MN, USA
NOT FOUND: I-20, EXIT 5A & US-61/SR-27, Vicksburg, MS, USA
NOT FOUND: I-95, EXIT 13, Elizabeth, NJ, USA
NOT FOUND: I-78, EXIT 58 & SR-9/SR-1, Newark, NJ, USA
NOT FOUND: I-88, EXIT 15 & SR-23, Oneonta, NY, USA
NOT FOUND: I-90, EXIT 69 & SR-82, Mauston, WI, USA
NOT FOUND: I-295, EXIT 3, Disputanta, VA, USA
SUCCESS: US-22, Duncansville, PA, USA -> (40.427234, -78.440876)
NOT FOUND: I-94, EXIT 166, Bismarck, ND, USA
NOT FOUND: I-695, EXIT 41 & SR-151, Dundalk, MD, USA
NOT FOUND: I-75, EXIT47 & SR-85, Detroit, MI, USA
NOT FOUND: I-20, EXIT 470, Dallas, TX, USA
SUCCESS: US-131 & SR-46, Cedar Springs, MI, USA -> (43.223360, -85.551424)
NOT FOUND: I-20 & SR-137, EXIT 138, Rayville, LA, USA
NOT FOUND: US-43/US-278/SR-171, Hamilton, AL, USA
NOT FOUND: I-40, EXIT 13 & US-71, Alma, AR, USA
NOT FOUND: I-95, EXIT 98 & SR-30, Doswell, VA, USA
NOT FOUND: I-20/I-59, EXIT 104, Mc Calla, AL, USA
NOT FOUND: I-95, EXIT 164 & US-52, Florence, SC, USA
NOT FOUND: I-55, EXIT 265 & SR-4, Senatobia, MS, USA
NOT FOUND: I-85, EXIT 102, Blacksburg, SC, USA
SUCCESS: SR-15 & CR-52, Truman, MN, USA -> (43.827742, -94.438934)
NOT FOUND: I-94/US-41, EXIT 329, Franksville, WI, USA
NOT FOUND: I-40, EXIT 107 & SR-95, Morrilton, AR, USA
NOT FOUND: I-20, EXIT 3 & SR-79, Greenwood, LA, USA
NOT FOUND: I-10, EXIT 31, Gulfport, MS, USA
NOT FOUND: I-80, EXIT 352, Wells, NV, USA
NOT FOUND: I-80, EXIT 292, Davenport, IA, USA
NOT FOUND: I-215, EXIT 21, Salt Lake City, UT, USA
NOT FOUND: I-75 & SR-613, EXIT 164, Findlay, OH, USA
NOT FOUND: I-5, EXIT 208, Arlington, WA, USA
NOT FOUND: I-80, EXIT 97, Falls Creek, PA, USA
NOT FOUND: I-94, EXIT 45 & US-12/SR-29, Menomonie, WI, USA
NOT FOUND: I-15 & I-90, EXIT 122, Butte, MT, USA
NOT FOUND: I-65, EXIT 322, Falkville, AL, USA
NOT FOUND: I-80, EXIT 46, Fernley, NV, USA
NOT FOUND: I-75, EXIT 350 & SR-2, Ringgold, GA, USA
NOT FOUND: I-95, EXIT 14, Woodbine, GA, USA
SUCCESS: I-10 & SR-108, EXIT 23, Sulphur, LA, USA -> (29.595331, -89.846096)
NOT FOUND: I-55, EXIT 52/SR-P, New Madrid, MO, USA
SUCCESS: US-11, Hattiesburg, MS, USA -> (31.260131, -89.337294)
NOT FOUND: I-95, EXIT 106, Kenly, NC, USA
NOT FOUND: I-35, EXIT 410 & US-77, Red Oak, TX, USA
NOT FOUND: US-41, EXIT 113 & SR-26, Oshkosh, WI, USA
NOT FOUND: I-70, EXIT 178 & SR-209, Cambridge, OH, USA
NOT FOUND: I-35, EXIT 32, Ardmore, OK, USA
NOT FOUND: I-44, EXIT 4 (ST 435), Joplin, MO, USA
SUCCESS: US-130, Burlington, NJ, USA -> (40.076342, -74.844872)
NOT FOUND: I-15, EXIT 48, North Las Vegas, NV, USA
SUCCESS: ST 220 & I-180, Muncy, PA, USA -> (41.204840, -76.787099)
NOT FOUND: I-40, EXIT 84, Russellville, AR, USA
NOT FOUND: I-95, EXIT 100 & SR-272, North East, MD, USA
NOT FOUND: I-20, EXIT 70, Columbia, SC, USA
NOT FOUND: US-287/US-82/SR-79 & US-281, Wichita Falls, TX, USA
NOT FOUND: I-80, EXIT 136, Des Moines, IA, USA
NOT FOUND: I-75, EXIT 135, Beaverdam, OH, USA
NOT FOUND: I-81, EXIT 52, Carlisle, PA, USA
NOT FOUND: I-94, EXIT 348, Fargo, ND, USA
NOT FOUND: I-64, EXIT 172, Grayson, KY, USA
NOT FOUND: I-85, EXIT 160, Carnesville, GA, USA
SUCCESS: US6-9 & US-75, Atoka, OK, USA -> (34.328495, -96.017838)
NOT FOUND: I-95, EXIT 6, Kingsland, GA, USA
NOT FOUND: I-70, EXIT 253, Salina, KS, USA
NOT FOUND: I-80, EXIT 201 & US-21, Brooklyn, IA, USA
NOT FOUND: HWY-401, EXIT 53B & HWY 1, Belleville, ON, USA
SUCCESS: SR-9, Maysville, KY, USA -> (38.647457, -83.764479)
NOT FOUND: I-65, RAYMOND EXIT, Indianapolis, IN, USA
NOT FOUND: I-20, EXIT 349, Ranger, TX, USA
NOT FOUND: I-20 & I-55, EXIT 47, Pearl, MS, USA
NOT FOUND: I-55, EXIT 58, Matthews, MO, USA
NOT FOUND: I-40, EXIT 255, Winslow, AZ, USA
SUCCESS: US-84 & US-385, Littlefield, TX, USA -> (33.918917, -102.332836)
NOT FOUND: ROUTE 17, EXIT 59-A, Sayre, PA, USA
NOT FOUND: I-75, EXIT 368, Reddick, FL, USA
NOT FOUND: I-15, EXIT 56 N, Dillon, MT, USA
NOT FOUND: I-435, EXIT 57, Kansas City, MO, USA
NOT FOUND: I-75, EXIT 122 & SR-61, Clinton, TN, USA
NOT FOUND: I-45, EXIT 178, Buffalo, TX, USA
NOT FOUND: I-94, EXIT 88, Osseo, WI, USA
NOT FOUND: I-285 , EXIT 51, Atlanta, GA, USA
SUCCESS: US-2/US-41, Rapid River, MI, USA -> (45.925200, -86.985988)
NOT FOUND: I-75, EXIT 285 & SR-52, San Antonio, FL, USA
SUCCESS: US-84 & US-27, Bainbridge, GA, USA -> (30.903825, -84.575477)
NOT FOUND: I-80, EXIT 342, Henderson, NE, USA
NOT FOUND: I-24, EXIT 81 SE, Murfreesboro, TN, USA
NOT FOUND: I-10, EXIT 142 & SR-71, Marianna, FL, USA
NOT FOUND: I-49/US-71, EXIT167 & CR-J, Peculiar, MO, USA
NOT FOUND: I-40, EXIT 153, Albuquerque, NM, USA
SUCCESS: US-72 & SR-247, Tuscumbia, AL, USA -> (34.731881, -87.702863)
NOT FOUND: I-40, EXIT 37 & US-219, Ozark, AR, USA
NOT FOUND: I-87, EXIT 36, Plattsburgh, NY, USA
NOT FOUND: I-75, EXIT 2, Lake Park, GA, USA
NOT FOUND: I-44, EXIT 11A & US-71/SR-249 & SR-FF, Joplin, MO, USA
NOT FOUND: I-35, EXIT 13, Laredo, TX, USA
SUCCESS: I-35, EXIT 8, Laredo, TX, USA -> (27.589719, -99.497028)
NOT FOUND: I-15, EXIT 4, Saint George, UT, USA
NOT FOUND: I-95, EXIT 29, Brunswick, GA, USA
NOT FOUND: SR-50, Yankton, SD, USA
NOT FOUND: I-94, EXIT 42, Belfield, ND, USA